export const products = [
    {
        id: 1,
        path: "/product",
        name: "boAt Rockerz 255 Pro+",
        details: "60HRS Battery, Fast Charge, IPX7, Dual Pairing, Low Latency, Magnetic Earbuds, Bluetooth",
        price: "Rs.2,500",
        discount: "Rs.3,499",
        rating: 4.5,
        reviews: "2,05,865",
        image: "/images/1.jpg",
    },
    {
        id: 2,
        path: "/product",
        name: "boAt Airdopes 141",
        details: "boAt Airdopes 141, Low Latency, ENx Tech, 42HRS Battery, Fast Charge, IWP, IPX4, v5.1 Bluetooth Earbuds,",
        price: "Rs.1,999",
        discount: "Rs.2,499",
        rating: 4.3,
        reviews: "1,84,389",
        image: "/images/2.jpg",
    },
    {
        id: 3,
        path: "/product",
        name: "boAt Bassheads 100",
        details: "boAt Bassheads 100 in Ear Wired Earphones with Mic(Black)",
        price: "Rs.3,555",
        discount: "Rs.4,499",
        rating: 4.2,
        reviews: "4,10,805",
        image: "/images/3.jpg",
    },
    {
        id: 4,
        path: "/product",
        name: "boAt Bassheads 100",
        details: "boAt Airdopes 141, Low Latency, ENx Tech, 42HRS Battery, Fast Charge, IWP, IPX4, v5.1 Bluetooth Earbuds,",
        price: "Rs.1,800",
        discount: "Rs.2,499",
        rating: 4.2,
        reviews: "4,10,805",
        image: "/images/4.jpg",
    },
    {
        id: 5,
        path: "/product",
        name: "boAt Bassheads 100",
        details: "boAt [New Launch] Airdopes 91 Prime, 45HRS Battery, 13mm Drivers, Metallic Finish, Low Latency,ENx Tech, Fast",
        price: "Rs.1,799",
        discount: "Rs.2,200",
        rating: 4.2,
        reviews: "4,10,805",
        image: "/images/5.jpg",
    }
]

export const productDetails = [
    {
        id: 1,
        image: "/images/1.jpg",
        detail: "boAt Airdopes 91 Prime, 45HRS Battery, 13mm Drivers, Metallic Finish, Low Latency,ENx Tech, Fast Charge, v5.3 Bluetooth TWS in Ear Earbuds Wireless Earphones with mic (Midnight Black)",
        link: "Visit the boAt Store",
        rate: "3.2",
        sell: "5K+ bought in past month",
        badge: "limited time offer",
        discount: "-80%",
        amount: "₹799",
        mrp: "₹3,990",
        tax: "Inclusive of all taxes"
    },
    {
        id: 2,
        image: "/images/2.jpg",
        detail: "boAt Rockerz 255 Pro+, 60HRS Battery, Fast Charge, IPX7, Dual Pairing, Low Latency, Magnetic Earbuds, Bluetooth Neckband, Wireless with Mic Earphones (Active Black)",
        link: "Visit the boAt Store",
        rate: "4.0",
        sell: "5K+ bought in past month",
        discount: "-75%",
        amount: " ₹998",
        mrp: "₹3,990",
        tax: "Inclusive of all taxes"
    },
    {
        id: 3,
        image: "/images/3.jpg",
        detail: "boAt Bassheads 100 in Ear Wired Earphones with Mic(Black)",
        link: "Visit the boAt Store",
        rate: "4.1",
        sell: "5K+ bought in past month",
        badge: "#Best Seller",
        discount: "-70%",
        amount: "₹299",
        mrp: "₹999",
        tax: "Inclusive of all taxes"
    },
    {
        id: 4,
        image: "/images/4.jpg",
        detail: "boAt Airdopes 311 Pro, 50HRS Battery, Fast Charge, Dual Mics ENx Tech, Transparent LID, Low Latency, IPX4, IWP Tech, v5.3 Bluetooth Earbuds, TWS Ear Buds Wireless Earphones with mic (Active Black)",
        link: "Visit the boAt Store",
        rate: "3.7",
        sell: "5K+ bought in past month",
        badge: "limited time offer",
        discount: "-82%",
        amount: "₹899",
        mrp: "₹4,990",
        tax: "Inclusive of all taxes"
    },
    {
        id: 5,
        image: "/images/5.jpg",
        detail: "boAt Airdopes 141, Low Latency, ENx Tech, 42HRS Battery, Fast Charge, IWP, IPX4, v5.1 Bluetooth Earbuds, TWS Ear Buds Wireless Earphones with mic (Bold Black)",
        link: "Visit the boAt Store",
        rate: "3.8",
        sell: "5K+ bought in past month",
        badge: "limited time offer",
        discount: "-78%",
        amount: "₹999",
        mrp: "₹4,490",
        tax: "Inclusive of all taxes"
    }
]